# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'custom_setup.sh'
- task: Bash@3
  name: mvnsetup
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/custom_setup.sh'
# - task: Bash@3
#   inputs:
#     filePath: '$(System.DefaultWorkingDirectory)'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    #options: '-X -B -s $(mvnSettings.secureFilePath)'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

variables:
- name: appVersion
  value: 1.0
- name: bNumber
  value: $(Build.BuildNumber)
- task: AzureCLI@2
  inputs:
   # azureSubscription: ''
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      #!/bin/sh
      appVersion=$1
      buildNo=$2    
      echo printing values:
      echo appVersion= "$appVersion"
      echo buildNo= "$buildNo"
    arguments: '''${{ variables.appVersion }} ${{ variables.bNumber }}'''




- task: DownloadSecureFile@1
  inputs:
    secureFile: 'custom-script.sh'
# - task: Bash@3
#   name: mvnbuild
#   inputs:
#     filePath: '$(System.DefaultWorkingDirectory)/custom-script.sh'

- task: CopyFiles@2
  inputs:
    Contents: '**/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: deploy'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
   # ArtifactName: 'deploy'
   # publishLocation: 'Container'
