# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      #!/bin/sh
      #set -x
      export CICD_DIR=$(readlink -f "./.cicd")
      mkdir -p $CICD_DIR
      export M2_HOME=${bamboo_capability_system_builder_mvn3_Maven_3}
      export PATH=$PATH:${M2_HOME}/bin
      mvn --version
      uuid=$(uuidgen)
      master=$(mvn --encrypt-master-password ${uuid})
      cat >${CICD_DIR}/settings-security.xml <<EOL
      <settingsSecurity>
      <master>${master}</master>
      </settingsSecurity>
      EOL
      chmod 600 ${CICD_DIR}/settings-security.xml
      password=$(mvn -Dsettings.security=${CICD_DIR}/settings-security.xml -ep
      "${service_account_password}")
      cat >${CICD_DIR}/settings.xml <<EOL
      <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
      http://maven.apache.org/xsd/settings-1.0.0.xsd">
      <servers>
      <server>
      <id>artifactory</id>
      <username>${account_username}</username>
      <password>${password}</password>
      </server>
      </servers>
      <mirrors>
      <mirror>
      <id>artifactory</id>
      <name>Artifactory_Staging-releases</name>
      <url>https://artifactory/</url>
      <mirrorOf>central</mirrorOf>
      </mirror>
      </mirrors>
      </settings>
      EOL
      chmod 600 ${CICD_DIR}/settings.xml
      cat >${CICD_DIR}/build.properties <<EOF
      MAVEN_EXEC=${M2_HOME}/bin/mvn
      MAVEN_SETTINGS=${CICD_DIR}/settings.xml
      MAVEN_SECURITY_SETTINGS=${CICD_DIR}/settings-security.xml
      CICD_DIR=${CICD_DIR}
      EOF
#- task: Maven@3
- task: Maven@3.205.1
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CopyFiles@2
  inputs:
    Contents: '**/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: deploy'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
   # ArtifactName: 'deploy'
   # publishLocation: 'Container'
