# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'custom_setup.sh'
- task: Bash@3
  name: mvnsetup
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/custom_setup.sh'
    workingDirectory: .cicd/build.properties
    bashEnvValue: $(workingDirectory)
# - task: Bash@3
#   inputs:
#     filePath: '$(System.DefaultWorkingDirectory)'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'custom-script.sh'
- task: Bash@3
  inputs:
    workingDirectory: .cicd/build.properties
    filePath: '$(System.DefaultWorkingDirectory)/custom-script.sh'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    #options: '-X -B -s $(mvnSettings.secureFilePath)'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- script: echo '$(Build.BuildNumber)'
- script: git rev-parse HEAD
- script: git branch -r

  




- task: DownloadSecureFile@1
  inputs:
    secureFile: 'custom-script.sh'
# - task: Bash@3
#   name: mvnbuild
#   inputs:
#     filePath: '$(System.DefaultWorkingDirectory)/custom-script.sh'

- task: CopyFiles@2
  inputs:
    Contents: '**/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: deploy'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
   # ArtifactName: 'deploy'
   # publishLocation: 'Container'
